### ISSUE TITLE
Smoke test for IP (Nicholas)

### ISSUE THREAD

**Issue by Nicklelodeon** [AY2223S2-CS2103-F10-1/tp#1]
[duke.jar.zip](https://github.com/AY2223S2-CS2103-F10-1/tp/files/10753264/duke.jar.zip)

**Comment by cyiting** [comment]
[duke.jar.zip](https://github.com/AY2223S2-CS2103-F10-1/tp/files/10757764/duke.jar.zip)

**Comment by Guo-KeCheng** [comment]
[duke.zip](https://github.com/AY2223S2-CS2103-F10-1/tp/files/10762428/duke.zip)

**Comment by Nicklelodeon** [comment]
[duke.jar.zip](https://github.com/AY2223S2-CS2103-F10-1/tp/files/10762810/duke.jar.zip)

Updated duke.jar

**Comment by Nicklelodeon** [comment]
[duke.jar.zip](https://github.com/AY2223S2-CS2103-F10-1/tp/files/10762828/duke.jar.zip)

updated duke.jar

**Comment by Nicklelodeon** [comment]
[duke.jar.zip](https://github.com/AY2223S2-CS2103-F10-1/tp/files/10762843/duke.jar.zip)

updated duke.jar

**Comment by Nicklelodeon** [comment]
version 3
[duke.jar.zip](https://github.com/AY2223S2-CS2103-F10-1/tp/files/10762995/duke.jar.zip)

**Comment by cyiting** [comment]
[duke.jar.zip](https://github.com/AY2223S2-CS2103-F10-1/tp/files/10763877/duke.jar.zip)
