### ISSUE TITLE
Refactor code according to Law of Demeter

### ISSUE THREAD

**Issue by Nicklelodeon** [AY2223S2-CS2103-F10-1/tp#100]

**Comment by kayyenl** [comment]
To make sure most of our code (and also from now on) doesn't break the Law of Demeter! It is as follows: 


> Law of Demeter (LoD):

- An object should have limited knowledge of another object.
- An object should only interact with objects that are closely related to it.

Also known as

- Don't talk to strangers
- Principle of least knowledge

**Comment by SPWwj** [comment]
Looks like there will be a lot of amendment in OfficeConnectModel.class
