### ISSUE TITLE
[PE-D][Tester A] Quickstart Guide is not maximisable

### ISSUE THREAD

**Issue by nus-pe-script** [AY2223S2-CS2103-F10-1/tp#189]
Currently, quickstart guide which contains application screenshots is not maximisable. This may make it hard for the user to see the details of each GUI component throughout the guide.

![Screenshot 2023-03-31 at 2.19.59 PM.png](https://raw.githubusercontent.com/afiqzu/ped/main/files/3c6cb95b-e01c-4718-b4a6-db27d1c9f76e.png)

-------------
Labels: `type.FeatureFlaw` `severity.Low`
original: afiqzu/ped#1

**Comment by kayyenl** [comment]
Resolved, trivial issue which only needs explanation
