### ISSUE TITLE
[PE-D][Tester F] More screenshots for 3.4 and 3.5

### ISSUE THREAD

**Issue by nus-se-script** [AY2223S2-CS2103-F10-1/tp#225]
Not many screenshots. Hard to understand what is the expected behavior as there is no point of reference. 

-------------
Labels: `severity.Low` `type.DocumentationBug`
original: ruiyigan/ped#14

**Comment by kayyenl** [comment]
Just change Assigning and Completion Tasks to Assigning and MARKING tasks
