### ISSUE TITLE
Should an invalid "review" flush out the display like an invalid "find"

### ISSUE THREAD

**Issue by Guo-KeCheng** [AY2223S2-CS2103-F10-1/tp#80]
An invalid `find` empties out the GUI and display 0 person found.

Should we do the same for an invalid `review`/`reviewtask`?

For now, I retained the list even if the `review`/`reviewtask` is invalid. Only an error message is displayed.

**Comment by Nicklelodeon** [comment]
I think an error would be better? As it tells the user that their input is invalid

**Comment by SPWwj** [comment]
Strongly agree to consider a flush out display for invalid "find", it will definitely enhance the user experiance.
